name: ci

on:
  push:
    branches:
      - 'main'
  schedule:
    # run every month to rebuild on the latest tag
    - cron: '0 0 1 * *'

jobs:
  docker:
    runs-on: ubuntu-latest
    env:
      DOCKER_USERNAME: iloveitaly
    strategy:
      fail-fast: false
      matrix:
        # TODO update these variants as time goes on
        variant: [0-ubuntu-22.04, 0-ubuntu, 0-debian, buster, bullseye]
    steps:
      - uses: actions/checkout@v4
      -
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ github.event.repository.name }}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          # https://github.com/iloveitaly/asdf-devcontainer/settings/secrets/actions
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          # amd64 supports x86_64
          platforms: linux/amd64,linux/arm64
          tags: ${{ github.event.repository.full_name }}:${{ matrix.variant }}
          labels: ${{ steps.meta.outputs.labels }}
      -
        name: Update repo description
        uses: peter-evans/dockerhub-description@v3.4.2
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          short-description: ${{ github.event.repository.description }}
      - uses: gautamkrishnar/keepalive-workflow@v1
